# Generated by Django 4.2.30 on 2026-06-01 08:30

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceGroup",
            fields=[
                (
                    "group_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="组ID"
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="组名称"
                    ),
                ),
                (
                    "group_parent_id",
                    models.BigIntegerField(default=0, verbose_name="父级id"),
                ),
                ("group_sort", models.IntegerField(default=1, verbose_name="排序")),
                ("group_level", models.IntegerField(default=1, verbose_name="层级")),
                (
                    "ding_webhook",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="钉钉webhook地址"
                    ),
                ),
                (
                    "feishu_webhook",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="飞书webhook地址"
                    ),
                ),
                (
                    "qywx_webhook",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="企业微信webhook地址"
                    ),
                ),
                (
                    "is_deleted",
                    models.IntegerField(
                        choices=[(0, "否"), (1, "是")],
                        default=0,
                        verbose_name="是否删除",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("sys_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "资源组管理",
                "verbose_name_plural": "资源组管理",
                "db_table": "resource_group",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="实例名称"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("master", "主库"), ("slave", "从库")],
                        max_length=6,
                        verbose_name="实例类型",
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("mssql", "MsSQL"),
                            ("redis", "Redis"),
                            ("pgsql", "PgSQL"),
                            ("oracle", "Oracle"),
                            ("mongo", "Mongo"),
                            ("phoenix", "Phoenix"),
                            ("odps", "ODPS"),
                            ("clickhouse", "ClickHouse"),
                        ],
                        max_length=20,
                        verbose_name="数据库类型",
                    ),
                ),
                ("host", models.CharField(max_length=200, verbose_name="实例连接")),
                ("port", models.IntegerField(default=0, verbose_name="端口")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "resource_group",
                    models.ManyToManyField(
                        blank=True,
                        to="resource_management.resourcegroup",
                        verbose_name="资源组",
                    ),
                ),
            ],
            options={
                "verbose_name": "实例配置",
                "verbose_name_plural": "实例配置",
                "db_table": "sql_instance",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        default="", max_length=50, verbose_name="显示的中文名"
                    ),
                ),
                (
                    "ding_user_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="钉钉UserID"
                    ),
                ),
                (
                    "wx_user_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="企业微信UserID"
                    ),
                ),
                (
                    "feishu_open_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="飞书OpenID"
                    ),
                ),
                (
                    "failed_login_count",
                    models.IntegerField(default=0, verbose_name="失败计数"),
                ),
                (
                    "last_login_failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次失败登录时间"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "resource_group",
                    models.ManyToManyField(
                        blank=True,
                        to="resource_management.resourcegroup",
                        verbose_name="资源组",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户管理",
                "verbose_name_plural": "用户管理",
                "db_table": "sql_users",
                "managed": True,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
